### ISSUE TITLE
Main Website bug?

### ISSUE THREAD

**Issue by zikrimarquel** [aurelia/loader-webpack#10]
I recently know aurelia from quora, and when i opened the main website(aurelia.io). It seems the website having a trouble.
![selection_009](https://cloud.githubusercontent.com/assets/7337736/15972027/5756a9b2-2f66-11e6-93d8-b84def954a9b.png)

**Comment by EisenbergEffect** [comment]
Tha's odd. The video is hosted on Vimeo, so perhaps there was a temporary service issue with them? I just checked it now and it seems fine.

**Comment by zikrimarquel** [comment]
Oh so it's a video from vimeo? Sorry for the misunderstanding. For your information, vimeo is blocked in my country.
