### ISSUE TITLE
@noView not loading in Webpack

### ISSUE THREAD

**Issue by JohnCampionJr** [aurelia/loader-webpack#22]
**I'm submitting a bug report**
- **Library Version:**
  1.0.3

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  6.9.1 LTS
- **NPM Version:**
  3.10.9
- **JSPM OR Webpack AND Version**
  webpack 2.1.0-beta.25
- **Browser:**
  all 
- **Language:**
  TypeScript 2.0

**Current behavior:**
@noView(['nprogress/nprogress.css'])
seems to be ignore by the webpack loader.  The resulting app fails to load trying to find nprogress.css

Workaround, inside matching html file solves this:

`
<template>
    <require from="nprogress/nprogress.css"></require>    
</template>
`

**Expected/desired behavior:**
- **What is the expected behavior?**
  To include the nprogress.css and adjust the @noview to read it.
- **What is the motivation / use case for changing the behavior?**
  Being able to use the noview attribute with webpack

**Comment by niieani** [comment]
This is not a bug, you are missing a build resource declaration (see http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/bundling-webpack/6). Matching HTML just makes the webpack plugin automatically read all the `require from` to include the build resource. You can simply add your CSS file as a build resource to `package.json`, no need to create a matching HTML file.
