### ISSUE TITLE
[Question] No view model found in module "app"

### ISSUE THREAD

**Issue by dev0x10** [aurelia/loader-webpack#23]
**I'm submitting a bug report**

* **Library Version:**
1.0.3

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.1

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.7

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.22

* **Browser:**
Firefox 49.0.2

* **Language:**
ESNext

**Current behavior:**
Cannot load app view

**Expected/desired behavior:**

App view loaded successfully

* **What is the expected behavior?**
App view loaded successfully

So, I try to load my Aurelia app inside an iFrame. For Chrome it works fine without any problem but Firefox throwing error "**No view model common found in module "app".**"

I debug a little bit and end up in this method
```javascript
WebpackLoader.prototype._import = function _import(moduleId) {
    var _this2 = this;

    if (this.modulesBeingLoaded[moduleId]) {
      return this.modulesBeingLoaded[moduleId];
    }
    var moduleIdParts = moduleId.split('!');
    var path = moduleIdParts.splice(moduleIdParts.length - 1, 1)[0];
    var loaderPlugin = moduleIdParts.length === 1 ? moduleIdParts[0] : null;

    var action = new Promise(function (resolve, reject) {
      if (loaderPlugin) {
        try {
          return resolve(_this2.loaderPlugins[loaderPlugin].fetch(path));
        } catch (e) {
          return reject(e);
        }
      } else {
        try {
          var result = __webpack_require__(path);
          return _this2._getActualResult(result, resolve, reject);
        } catch (_) {
          delete __webpack_require__.c[path];
        }
        require.ensure([], function (require) {
          var result = require('aurelia-loader-context/' + path);
//----------------------------------------------------------
// in here, var result is 'undefined' and path value is 'app'
// Chrome doesn't enter this function
//----------------------------------------------------------
          return _this2._getActualResult(result, resolve, reject);
        }, 'app');
      }
    }).then(function (result) {
      _this2.modulesBeingLoaded[moduleId] = undefined;
      return result;
    });
    this.modulesBeingLoaded[moduleId] = action;
    return action;
  };
``` 
If the page loaded outside iFrame, there is no problem at all.

**Comment by niieani** [comment]
The new, experimental Webpack-Aurelia stack should fix this. Will be available soon.

**Comment by dev0x10** [comment]
@niieani could you tell me where is the problem because I haven't debug it deeper.
 Is there any workaround?

**Comment by niieani** [comment]
Fixed by https://github.com/aurelia/skeleton-navigation/pull/714
