### ISSUE TITLE
Module not found: Error: Can't resolve 'css'

### ISSUE THREAD

**Issue by heruan** [aurelia/loader-webpack#27]
Suddenly I get this warning:

```
WARNING in ./src ^\.\/.*$
Module not found: Error: Can't resolve 'css' in '/Users/lovatog/Workspaces/aurelia/packages/best-app/src'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders.
                 You need to specify 'css-loader' instead of 'css'.
 @ ./src ^\.\/.*$
 @ ./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js
 @ ./~/aurelia-bootstrapper-webpack/dist/commonjs/aurelia-bootstrapper-webpack.js
 @ ./src/main/index.ts
 @ multi app
```

Webpack's guys told me `aurelia-loader-webpack` may be missing `-loader` somewhere, which became mandatory for loaders in the latest betas.

**Comment by niieani** [comment]
I reckon you're not using easy-webpack which fixed this in a patch release.

Please add [this configuration property](https://github.com/easy-webpack/config-aurelia/blob/master/src/index.ts#L7-L13) to the options passed into AureliaWebpackPlugin and it'll work properly.

**Comment by niieani** [comment]
Solved by https://github.com/aurelia/webpack-plugin/releases/tag/1.2.0.
