### ISSUE TITLE
Upgrading app from v1.0.3 to v2.0.0 breaks my app

### ISSUE THREAD

**Issue by pndewit** [aurelia/loader-webpack#33]
**I'm submitting a bug report**

* **Library Version:**
2.0.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.3

* **Node Version:**
6.2.0

* **NPM Version:**
4.1.2

* **Browser:**
Chrome 55

**Current behavior:**
Updating from version 1.0.3 to 2.0.0 crashes my app at startup with the following error:
`Error: Unable to find module with ID: main` where `main` is my module ID. When I switch back to 1.0.3 it starts working again. Is there something I need to change when updating to the latest version? (I am not using HMR yet)

Some versions I am using that might be helpful:
- webpack: 2.2.1
- webpack-dev-server: 2.3.0
- aurelia-loader-webpack: 1.0.3 -> 2.0.0
- aurelia-bootstrapper: 2.0.1
- typescript: 2.1.5

If I need to post more information, please ask :)

**Comment by jods4** [comment]
The 2.0.0 webpack plugins have been completely redesigned. The major version bump reflects that they are not compatible with the previous ones. You will have to make several changes to get everything working.

At the moment the only documentation available is here:
https://github.com/jods4/aurelia-webpack-build/wiki

Please read it and look at the demos in the same repo. You can contact me if you have issues getting this to work.

**Comment by pndewit** [comment]
@jods4 I'll look into it. Nice work on those docs!!

Btw, I am familiar with semantic versioning. So I was (kind of) already expecting it to break, but I  upgraded some other packages (e.g. webpack, webpack-dev-server and aurelia-bootstrapper) some time ago and that didn't break anything for me (not something major at least). So I thought this had to do with just the latest aurelia-loader-webpack version, was I wrong in drawing this quick conclusion?

**Comment by jods4** [comment]
> So I thought this had to do with just the latest aurelia-loader-webpack version, was I wrong in drawing this quick conclusion?

Most probably not. 
`webpack` upgrade from 1.x to 2.x does break a few stuff, not much though.
The `aurelia-loader-webpack` 2.0.0 release is brand new and is (by design) not sharing any of the old configuration. So without adjustments it definitely _will_ break. This is for the better though, as I hope you'd find it much simpler to use.

Ping me on gitter if you need help.
