### ISSUE TITLE
Webpack log size problem

### ISSUE THREAD

**Issue by adriatic** [aurelia/loader-webpack#38]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
8.1.3

* **NPM Version:**
5.5.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

I am not sure what webpack version or even tool itself am I using. The README.md instructions state:
> This will install all required dependencies, including a local version of Webpack that is going to
build and bundle the app. There is no need to install Webpack globally

Also, the devDependencies section of package.json shows

    "@easy-webpack/config-aurelia": "^2.2.2",
    "@easy-webpack/config-babel": "^4.0.0",
    "@easy-webpack/config-common-chunks-simple": "^2.0.3",
    "@easy-webpack/config-copy-files": "^1.1.2",
    "@easy-webpack/config-css": "^4.0.0",
    "@easy-webpack/config-env-development": "^2.1.5",
    "@easy-webpack/config-env-production": "^3.0.0",
    "@easy-webpack/config-external-source-maps": "^3.1.0",
    "@easy-webpack/config-fonts-and-images": "^2.1.0",
    "@easy-webpack/config-generate-index-html": "^2.1.1",
    "@easy-webpack/config-global-bluebird": "^2.1.0",
    "@easy-webpack/config-global-jquery": "^2.1.0",
    "@easy-webpack/config-global-regenerator": "^1.2.2",
    "@easy-webpack/config-html": "^3.1.0",
    "@easy-webpack/config-json": "^3.1.0",
    "@easy-webpack/config-test-coverage-istanbul": "^3.2.0",
    "@easy-webpack/config-uglify": "^2.2.3",
    "@easy-webpack/core": "^2.0.0",

* **Browser:**
Chrome  62.0.3202.94

* **Language:**
ESNext

**Current behavior:**
Using the esnext-webpack skeleton, the command `npm start` results with well over thousand lines long output on the cmd.exe

**Expected/desired behavior:**

* **What is the expected behavior?**
A console log of a normal size (5-10) lines

* **What is the motivation / use case for changing the behavior?**

I am writing a set of tutorials and know that my readers will ask me about this behavior right away

**Comment by jods4** [comment]
We're in the process of replacing the old 1.x Aurelia webpack plugin with a new 2.0 release currently in Release Candidate form.
If you're writing tutorials, you really don't want to be using 1.x anymore as 2.0 is a complete rewrite meant to be more flexible and easier to use. More importantly, 2.0 is not backward compatible with a 1.x configuration.

Given all the `@easy-webpack` stuff I'm tempted to think you're using 1.x plugins.

There's no docs in the hub for now, but some background information on 2.0 is in its wiki:
https://github.com/aurelia/webpack-plugin/wiki

New skeletons are available, just be aware that they don't reference the latest RC:
https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-webpack

And some barebones, minimal examples can be found in my account:
https://github.com/jods4/aurelia-webpack-build/

**Comment by adriatic** [comment]
Thanks, @jods4 - more than **great** feedback. After discussing this situation pretty extensively (from the high level standpoint) with @EisenbergEffect, your more detailed comment will allow me to create the "alpha" versions of **[tutorial samples](https://github.com/aurelia-ui-toolkits/kendo-tutorials.code-2.0)** which target aurelia community developers using  **[aurelia kendoui bridge](aurelia-ui-toolkits.github.io/demo-kendo/)** plugin.

The current set of the **[tutorial samples](https://github.com/aurelia-ui-toolkits/kendo-tutorials.code-2.0)** are based on **[original skeletons ver 1.1.2](https://github.com/aurelia/skeleton-navigation/releases/tag/1.1.2)**, so I could appreciate your advice on how to proceed from this point onwards:

1. Rewrite the webpack targeting subset of my **[tutorial samples](https://github.com/aurelia-ui-toolkits/kendo-tutorials.code-2.0)**, using **["your webpack"](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-webpack)** samples as the basis

2. Rewrite all of my **[tutorial samples](https://github.com/aurelia-ui-toolkits/kendo-tutorials.code-2.0)** using the current **[master](https://github.com/aurelia/skeleton-navigation)** as the basis.

Also, please be aware of my work on **[cli-based-skeletons](https://github.com/aurelia-tools/cli-based-skeletons)** which I initiated with the intent to help @jeroenvinke at the time he worked on cli last, and the now generally accepted idea to "teach" cli to be able to generate all today's skeleton was not generally accepted. Since Jeroen is on "college hiatus", it may be worthwhile to point out to this work - and I would certainly appreciate some feedback to that. The documents describing these skeletons exist **[here](https://adriatic.gitbooks.io/aurelia-cli/content/)**

**Comment by jods4** [comment]
@adriatic My demos and the new skeletons should be similar when it comes to core Webpack features and both can be an inspiration. Just keep in mind that they don't have the same purpose or goal.

Skeletons are full featured setups that intent to include development config, production build, end-to-end testing and more. They have lots of dependencies on 3rd party libs and tie everything together in a large config. Obviously, they are opiniated and some choices were made that may not be everyone's.

My demos are minimal examples that demonstrate one specific aspect of the webpack plugin. They show how to get something working with as little code as possible and illustrate configuration for some specific use cases. I think they are a great "getting started" or learning tool, probably a little lightweight when it comes to building a large-scale app. None of them include automated tests for example. Only one of them has minification. And so on.

**Comment by adriatic** [comment]
Thanks, @jods4 - based on your explanation, what you have is perfectly fitting my needs. So, I will use is **[here](https://github.com/aurelia-ui-toolkits/kendo-tutorials.code-2.0/tree/master/skeleton-esnext-webpack)** and **[here](https://github.com/aurelia-ui-toolkits/kendo-tutorials.code-2.0/tree/master/skeleton-typescript-webpack)**, writing the same caveats you just stated yourself. 

If you care to see what I will do with them, I will share my experience **[here](https://github.com/aurelia-ui-toolkits/kendo-tutorials.code-2.0/issues/3)**

**Comment by jods4** [comment]
I'm glad it helped.
Shall we close this issue then?

**Comment by adriatic** [comment]
It's really bad that GitHub does not create email notifications about added comments to any given thread 😞 . So, with apologies for being late, let's close this issue.

I would also like to share with you my success in using this new Webpack plugin in my **[Aurelia CLI Adventures](https://www.gitbook.com/read/book/adriatic/aurelia-cli)** which is my attempt to peek in the near future when Aurelia CLI will be able to generate all Navigation Skeletons from scratch (by describing the process of hand-assembling these skeletons).
