### ISSUE TITLE
Code split module doesn't get updated in HMR mode

### ISSUE THREAD

**Issue by jussimattila** [aurelia/loader-webpack#39]
**I'm submitting a bug report**

* **Library Version:**
2.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.7.1

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
webpack 2.3.3

* **Browser:**
all  (tested on Chrome 64 | Firefox  58)

* **Language:**
TypeScript 2.2.2

**Current behavior:**
Hot module replacement of TypeScript source code doesn't work with Aurelia modules that have been split to a separate file using `PLATFORM.modulesName(...)` overload with chunk parameter, e.g.  `PLATFORM.moduleName(/* module */ '../counter/counter', /* chunk */ 'counter')`. Removing the second argument (`'counter'`) allows HMR to work normally.

**To reproduce:**

Create a new aurelia application using Microsoft's SpaTemplates: `dotnet new aurelia`. You may need to install the templates first using `dotnet new -i "Microsoft.AspNetCore.SpaTemplates::*"`. After the project is created, `npm install` dependencies.

Make one change in `app.ts`, modify line 20 to: ` moduleId: PLATFORM.moduleName('../counter/counter', 'counter'),`, i.e. add the chunk name argument.
Run the application with HMR. Load counter page and click on the increment button to see it add 1 to counter. Now change code in `counter.ts` from ` this.currentCount += 1;` to `this.currentCount += 10;` and save changes. HMR kicks in and does something, but falls short on actually updating the application. Click on the increment button and see that it is still adding only 1, not 10.

* **What is the expected behavior?**

Changes in TypeScript source code should be reflected in the running application through HMR. Change to the increment code should affect the result from clicking on the increment button.

* **What is the motivation / use case for changing the behavior?**

I wan't to develop modules using code splitting and with HMR enabled.

* **To fix**
Change this line:
https://github.com/aurelia/loader-webpack/blob/master/src/aurelia-loader-webpack.ts#L131
from:
`module.hot.accept(asyncModuleId, () => {});`
to:
`module.hot.accept(asyncModuleId, () => this.hmrContext.handleModuleChange(moduleId, module.hot));`

I've not contributed to Aurelia, but here's a PR on my fork for the change that appears to fix this issue: https://github.com/jussimattila/loader-webpack/pull/1

**Comment by Alexander-Taran** [comment]
If you will consider providing a PR to this repo.. There are some guidelines on commit messages. Which help to build change log.

**Comment by jussimattila** [comment]
Sure, I didn't have time for it immediately, but if that is desired, I'll have a look at contribution guidelines and prepare a PR during this week.

**Comment by Alexander-Taran** [comment]
PR waiting.
@niieani  & @EisenbergEffect 
who can review it?

**Comment by niieani** [comment]
Not sure what was the reason I didn't handle async modules, but if it fixes the problem, then that's great, since it shouldn't cause any issues.
Thanks!
