### ISSUE TITLE
Feature Request: Hot loading of views and models

### ISSUE THREAD

**Issue by Jaans** [aurelia/loader-webpack#5]
I'm sure webpack hot loading feature impresses and speaks for itself. I know I am. 

Which brings me to dream about whether this would be possible to achieve with Aurelia models and views?

Found the following information about enabling hot module replacement / loading on webpack website, but sadly I'm out of my depth here: [Hot Module Replacement](https://webpack.github.io/docs/hot-module-replacement.html)

**Comment by efolio** [comment]
+1

**Comment by niieani** [comment]
Good news: We're investigating a possible implementation.

**Comment by JohnCampionJr** [comment]
Any luck on this?  Would be so great to have!

**Comment by niieani** [comment]
I will be focusing on this once I solve most of the current issues with the Webpack-Aurelia integration in November, as I'll need a solid architecture to build on. Hot reloading for Views will be available first, as that poses fewer challenges.

**Comment by JohnCampionJr** [comment]
Awesome, thanks!  Appreciate your hard work

**Comment by niieani** [comment]
We've had a breakthrough last night ;)

![Aurelia HMR](https://www.dropbox.com/s/kgv5xpik0pvhe7k/2016-11-23%2002.24.23.gif?dl=1)

Coming soon for all!

[Retweet](https://twitter.com/niieani/status/801236402281336837/photo/1) if you so desire. :)

CC for thumb uppers: @MrHayato, @heruan, @MarkHerhold, @atsu85, @tobias-kuendig, @nmocruz, @raiseandfall, @NunoCruzSW, @DerAlbertCom, @DaveEmmerson, @nmocruz, @shabalin, @JohnCampionJr
